### ISSUE TITLE
ItemController now checks if the account is a photographer, should this be an admin ?

### ISSUE THREAD

**Issue by woutie012006** [GuusHamm/PTS4#10]
This is more of a designchoice, and highly depends if the product owner is going to print out products or if the photographer is.

**Comment by woutie012006** [comment]
also, item does not currently have a creator...

**Comment by woutie012006** [comment]
@GuusHamm @teunw @binq1000

**Comment by binq1000** [comment]
We first need to make clear who is offering these items, if a photographer can create them, But generally i don't see a need for an item creator.
